### ISSUE TITLE
update to 4.6.0-0.okd-2021-01-23-132511 fails due to open-vm-tools already absent

### ISSUE THREAD

**Issue by RyuunoAelia** [openshift/okd#479]
**Describe the bug**

I am using 4.6.0-0.okd-2021-01-17-185703 that I had trouble to install due to the presence of open-vm-tools. Not that I am in that version and try to update to 4.6.0-0.okd-2021-01-23-132511 it fails because open-vm-tools is not installed... And I cannot install it since the files exist in the base FCOS image.

**Version**

UPI BareMetal update from 4.6.0-0.okd-2021-01-17-185703 to 4.6.0-0.okd-2021-01-23-132511

**How reproducible**

Install 4.6.0-0.okd-2021-01-17-185703 and try to update to 4.6.0-0.okd-2021-01-23-132511

**Log bundle**

relevant log:
```
$ oc -n openshift-machine-config-operator logs -f machine-config-daemon-rzhsl -c machine-config-daemon | head -n100                                                                                                         1 ↵
I0124 16:45:38.916354  361690 start.go:108] Version: machine-config-daemon-4.6.0-202006240615.p0-378-gead62052-dirty (ead62052138543eb3e19b4de493a94ed7c88b3b9)
I0124 16:45:38.918083  361690 start.go:121] Calling chroot("/rootfs")
I0124 16:45:38.918159  361690 rpm-ostree.go:261] Running captured: rpm-ostree status --json
I0124 16:45:38.941196  361690 daemon.go:226] Booted osImageURL: quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c ()
I0124 16:45:38.947676  361690 daemon.go:233] Installed Ignition binary version: 2.8.1
I0124 16:45:38.964068  361690 start.go:97] Copied self to /run/bin/machine-config-daemon on host
I0124 16:45:38.966264  361690 metrics.go:106] Registering Prometheus metrics
I0124 16:45:38.966314  361690 metrics.go:111] Starting metrics listener on 127.0.0.1:8797
I0124 16:45:38.967331  361690 update.go:1661] Starting to manage node: okd4-master-25
I0124 16:45:38.969043  361690 rpm-ostree.go:261] Running captured: rpm-ostree status
I0124 16:45:39.060393  361690 daemon.go:862] State: idle
Deployments:
* pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
              CustomOrigin: Managed by machine-config-operator
                 Timestamp: 2021-01-17T11:43:43Z
           LayeredPackages: NetworkManager-ovs glusterfs glusterfs-fuse qemu-guest-agent

  pivot://quay.io/openshift/okd-content@sha256:95034a94e28949af41a53b9efb2fbb0651454a7c37bab002b0646e73c4721829
              CustomOrigin: Managed by machine-config-operator
                 Timestamp: 2020-12-12T05:05:37Z
           LayeredPackages: NetworkManager-ovs glusterfs glusterfs-fuse open-vm-tools
                            qemu-guest-agent
I0124 16:45:39.060414  361690 rpm-ostree.go:261] Running captured: journalctl --list-boots
I0124 16:45:39.133258  361690 daemon.go:869] journalctl --list-boots:
-1 df8f697bbf724d5f90baaab0b3cb67d1 Wed 2021-01-20 01:06:28 UTC—Wed 2021-01-20 21:44:07 UTC
 0 257cb932d75649378301841cc566a856 Wed 2021-01-20 21:45:04 UTC—Sun 2021-01-24 16:45:39 UTC
I0124 16:45:39.133288  361690 rpm-ostree.go:261] Running captured: systemctl list-units --state=failed --no-legend
I0124 16:45:39.141003  361690 daemon.go:884] systemd service state: OK
I0124 16:45:39.141018  361690 daemon.go:616] Starting MachineConfigDaemon
I0124 16:45:39.141078  361690 daemon.go:623] Enabling Kubelet Healthz Monitor
I0124 16:45:39.978541  361690 daemon.go:397] Node okd4-master-25 is part of the control plane
I0124 16:46:02.543922  361690 daemon.go:815] Current config: rendered-master-b1d5a4357e85a929594a1abca7461e3f
I0124 16:46:02.543942  361690 daemon.go:816] Desired config: rendered-master-5cb0b39837ac2039c0b99ecf28f28f66
I0124 16:46:02.551219  361690 daemon.go:1085] Validating against current config rendered-master-b1d5a4357e85a929594a1abca7461e3f
I0124 16:46:02.559145  361690 daemon.go:1093] Validated on-disk state
I0124 16:46:02.559182  361690 update.go:431] Checking Reconcilable for config rendered-master-b1d5a4357e85a929594a1abca7461e3f to rendered-master-5cb0b39837ac2039c0b99ecf28f28f66
I0124 16:46:02.585890  361690 update.go:1661] Starting update from rendered-master-b1d5a4357e85a929594a1abca7461e3f to rendered-master-5cb0b39837ac2039c0b99ecf28f28f66: &{osUpdate:false kargs:false fips:false passwd:false files:false units:false kernelType:false extensions:true}
I0124 16:46:02.587499  361690 update.go:1661] Update prepared; beginning drain
E0124 16:46:03.494607  361690 daemon.go:344] WARNING: ignoring DaemonSet-managed Pods: openshift-cluster-node-tuning-operator/tuned-9jb5f, openshift-controller-manager/controller-manager-h58q4, openshift-dns/dns-default-7r6gh, openshift-image-registry/node-ca-2hcvz, openshift-machine-config-operator/machine-config-daemon-rzhsl, openshift-machine-config-operator/machine-config-server-4c7kn, openshift-monitoring/node-exporter-6pfbc, openshift-multus/multus-admission-controller-xhw7d, openshift-multus/multus-gnqf8, openshift-multus/network-metrics-daemon-m442k, openshift-sdn/ovs-sjwcj, openshift-sdn/sdn-bp7xx, openshift-sdn/sdn-controller-97wfv
I0124 16:46:03.494626  361690 update.go:1661] drain complete
I0124 16:46:03.496523  361690 update.go:167] Successful drain took 0.907432148 seconds
I0124 16:46:03.496561  361690 update.go:1048] Updating files
I0124 16:46:03.507190  361690 update.go:1384] Writing file "/etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt"
I0124 16:46:03.537544  361690 update.go:1384] Writing file "/etc/tmpfiles.d/cleanup-cni.conf"
I0124 16:46:03.582727  361690 update.go:1384] Writing file "/etc/kubernetes/static-pod-resources/configmaps/cloud-config/ca-bundle.pem"
I0124 16:46:03.598138  361690 update.go:1384] Writing file "/usr/local/bin/configure-ovs.sh"
I0124 16:46:03.626863  361690 update.go:1384] Writing file "/etc/containers/storage.conf"
I0124 16:46:03.658734  361690 update.go:1384] Writing file "/etc/NetworkManager/dispatcher.d/90-long-hostname"
I0124 16:46:03.690555  361690 update.go:1384] Writing file "/etc/systemd/system.conf.d/10-default-env-godebug.conf"
I0124 16:46:03.716421  361690 update.go:1384] Writing file "/etc/kubernetes/static-pod-resources/etcd-member/root-ca.crt"
I0124 16:46:03.742310  361690 update.go:1384] Writing file "/etc/modules-load.d/iptables.conf"
I0124 16:46:03.768196  361690 update.go:1384] Writing file "/etc/kubernetes/kubelet-ca.crt"
I0124 16:46:03.797334  361690 update.go:1384] Writing file "/etc/systemd/system.conf.d/kubelet-cgroups.conf"
I0124 16:46:03.843969  361690 update.go:1384] Writing file "/etc/NetworkManager/conf.d/sdn.conf"
I0124 16:46:03.876697  361690 update.go:1384] Writing file "/var/lib/kubelet/config.json"
I0124 16:46:03.906074  361690 update.go:1384] Writing file "/etc/kubernetes/manifests/recycler-pod.yaml"
I0124 16:46:03.947762  361690 update.go:1384] Writing file "/etc/kubernetes/ca.crt"
I0124 16:46:03.976996  361690 update.go:1384] Writing file "/etc/sysctl.d/forward.conf"
I0124 16:46:04.003028  361690 update.go:1384] Writing file "/etc/sysctl.d/inotify.conf"
I0124 16:46:04.035532  361690 update.go:1384] Writing file "/usr/local/bin/recover-kubeconfig.sh"
I0124 16:46:04.079446  361690 update.go:1384] Writing file "/usr/local/sbin/set-valid-hostname.sh"
I0124 16:46:04.126540  361690 update.go:1384] Writing file "/etc/kubernetes/kubelet-plugins/volume/exec/.dummy"
I0124 16:46:04.187444  361690 update.go:1384] Writing file "/etc/containers/registries.conf"
I0124 16:46:04.231752  361690 update.go:1384] Writing file "/etc/crio/crio.conf.d/00-default"
I0124 16:46:04.264022  361690 update.go:1384] Writing file "/etc/containers/policy.json"
I0124 16:46:04.296120  361690 update.go:1384] Writing file "/etc/kubernetes/cloud.conf"
I0124 16:46:04.341125  361690 update.go:1384] Writing file "/etc/kubernetes/kubelet.conf"
I0124 16:46:04.383008  361690 update.go:1384] Writing file "/etc/kubernetes/static-pod-resources/haproxy/haproxy.cfg.tmpl"
I0124 16:46:04.425794  361690 update.go:1384] Writing file "/etc/kubernetes/manifests/haproxy.yaml"
I0124 16:46:04.454560  361690 update.go:1384] Writing file "/etc/kubernetes/manifests/keepalived.yaml"
I0124 16:46:04.485005  361690 update.go:1384] Writing file "/etc/kubernetes/static-pod-resources/keepalived/keepalived.conf.tmpl"
I0124 16:46:04.529204  361690 update.go:1384] Writing file "/etc/haproxy/configuration-date"
I0124 16:46:04.559569  361690 update.go:1307] Writing systemd unit dropin "10-mco-default-env.conf"
I0124 16:46:04.590043  361690 update.go:1307] Writing systemd unit dropin "mco-disabled.conf"
I0124 16:46:04.619947  361690 update.go:1307] Writing systemd unit dropin "10-mco-default-env.conf"
I0124 16:46:04.665629  361690 update.go:1342] Writing systemd unit "kubelet.service"
I0124 16:46:04.694054  361690 update.go:1270] /etc/systemd/system/multi-user.target.wants/kubelet.service already exists. Not making a new symlink
I0124 16:46:04.694071  361690 update.go:1342] Writing systemd unit "machine-config-daemon-firstboot.service"
I0124 16:46:04.737305  361690 update.go:1270] /etc/systemd/system/multi-user.target.wants/machine-config-daemon-firstboot.service already exists. Not making a new symlink
I0124 16:46:04.737354  361690 update.go:1342] Writing systemd unit "machine-config-daemon-pull.service"
I0124 16:46:04.781140  361690 update.go:1270] /etc/systemd/system/multi-user.target.wants/machine-config-daemon-pull.service already exists. Not making a new symlink
I0124 16:46:04.781156  361690 update.go:1342] Writing systemd unit "node-valid-hostname.service"
I0124 16:46:04.810331  361690 update.go:1270] /etc/systemd/system/multi-user.target.wants/node-valid-hostname.service already exists. Not making a new symlink
I0124 16:46:04.810347  361690 update.go:1342] Writing systemd unit "nodeip-configuration.service"
I0124 16:46:04.838608  361690 update.go:1270] /etc/systemd/system/multi-user.target.wants/nodeip-configuration.service already exists. Not making a new symlink
I0124 16:46:04.838751  361690 update.go:1279] Enabled openvswitch.service
I0124 16:46:04.838774  361690 update.go:1342] Writing systemd unit "ovs-configuration.service"
I0124 16:46:04.866990  361690 update.go:1270] /etc/systemd/system/multi-user.target.wants/ovs-configuration.service already exists. Not making a new symlink
I0124 16:46:04.867008  361690 update.go:1307] Writing systemd unit dropin "10-ovs-vswitchd-restart.conf"
I0124 16:46:04.894980  361690 update.go:1307] Writing systemd unit dropin "10-ovsdb-restart.conf"
I0124 16:46:04.922755  361690 update.go:1279] Enabled ovsdb-server.service
I0124 16:46:04.922769  361690 update.go:1307] Writing systemd unit dropin "10-mco-default-env.conf"
I0124 16:46:04.952292  361690 update.go:1307] Writing systemd unit dropin "mco-controlplane-nice.conf"
I0124 16:46:04.984835  361690 update.go:1307] Writing systemd unit dropin "mco-disabled.conf"
I0124 16:46:05.014445  361690 update.go:1121] Deleting stale data
I0124 16:46:05.024578  361690 update.go:1492] Writing SSHKeys at "/home/core/.ssh/authorized_keys"
I0124 16:46:05.102356  361690 controlplane.go:42] Device /sys/devices/pci0000:00/0000:00:17.0/ata3/host2/target2:0:0/2:0:0:0/block/sda already uses scheduler bfq
I0124 16:46:05.102418  361690 run.go:18] Running: nice -- ionice -c 3 oc image extract --path /:/run/mco-machine-os-content/os-content-083590241 --registry-config /var/lib/kubelet/config.json quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
I0124 16:46:26.979008  361690 update.go:962] Applying extensions : ["update" "--uninstall" "open-vm-tools"]
I0124 16:46:27.010657  361690 update.go:375] Rolling back applied changes to OS due to error: failed to execute rpm-ostree ["update" "--uninstall" "open-vm-tools"] : exit status 1
```

```
[root@okd4-compute-201 core]# rpm-ostree "update" "--uninstall" "open-vm-tools"
error: Package/capability 'open-vm-tools' is not currently requested
```

**Comment by vrutkovs** [comment]
Check suggestions at https://github.com/openshift/okd/issues/471#issuecomment-766348026?

**Comment by RyuunoAelia** [comment]
I had to do something like what the update-{master,worker} scripts do. But it was not a single smooth execution and had to fight a bit to make MCO accept my version... This is because MCO updated the rendered config twice during the update process and the update process did not agree completely with the version of the rendered MachineConfig it wanted... (also rook-ceph did not help due to the PodDisruptionBudget and its heuristic for static placement of pods...).

I guess the process is "documented" in the suggestion.

**Comment by holgerstolzenberg** [comment]
@vrutkovs 

The suggested solution do not work for us. We are in the same situation trying to upgrade from `4.6.0-0.okd-2021-01-17-185703` => `4.6.0-0.okd-2021-01-23-132511`.

We had to manually remove the `open-vm-tools` package previously in order to get to release the given release (as suggested in #471).

Trying to upgrade now we are hitting this error. Trying to uninstall `open-vm-tools` package says it is not installed. Trying to install it again says it cannot be done due to the hardlinking issue (VGAuthService: File exists).

The I tried to use the suggested update worker/master scripts without success:
- as already found out master worker rendered config was messed up in the script
- The scripts are not fully working for us, the offending command `NODE=$(oc get node -l node-role.kubernetes.io/worker= -o=jsonpath='{.items[*].metadata.name}')` is not returning a single result

Then I tried using

```
# sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora{,-updates}.repo
# /run/bin/machine-config-daemon pivot quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4
# sed -i 's;enabled=0;enabled=1;g' /etc/yum.repos.d/fedora{,-updates}.repo
```

and ran into the following error:

```
[root@okd-pg-w-01 core]# sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora{,-updates}.repo
[root@okd-pg-w-01 core]# /run/bin/machine-config-daemon pivot quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4
I0125 06:43:55.435091  766318 run.go:18] Running: nice -- ionice -c 3 oc image extract --path /:/run/mco-machine-os-content/os-content-296672374 --registry-config /var/lib/kubelet/config.json quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4
I0125 06:44:20.762439  766318 rpm-ostree.go:261] Running captured: rpm-ostree status --json
I0125 06:44:20.864293  766318 rpm-ostree.go:179] Previous pivot: quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
I0125 06:44:22.782012  766318 rpm-ostree.go:216] No com.coreos.ostree-commit label found in metadata! Inspecting...
I0125 06:44:22.782053  766318 rpm-ostree.go:261] Running captured: ostree refs --repo /run/mco-machine-os-content/os-content-296672374/srv/repo
I0125 06:44:22.896930  766318 rpm-ostree.go:224] Using ref fedora/x86_64/coreos/stable
I0125 06:44:22.896977  766318 rpm-ostree.go:261] Running captured: ostree rev-parse --repo /run/mco-machine-os-content/os-content-296672374/srv/repo fedora/x86_64/coreos/stable
I0125 06:44:22.952729  766318 rpm-ostree.go:243] Executing rebase from repo path /run/mco-machine-os-content/os-content-296672374/srv/repo with customImageURL pivot://quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4 and checksum 4a5dccf92728fd13c944805aea5e3206d9292b401b075824a76713d9aa749d52
I0125 06:44:22.952762  766318 rpm-ostree.go:261] Running captured: rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-296672374/srv/repo:4a5dccf92728fd13c944805aea5e3206d9292b401b075824a76713d9aa749d52 --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4 --custom-origin-description Managed by machine-config-operator
error: Could not depsolve transaction; 1 problem detected:
 Problem: package NetworkManager-ovs-1:1.26.4-1.fc33.x86_64 requires openvswitch, but none of the providers can be installed
  - conflicting requests
  - nothing provides libunbound.so.8()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_acl.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bbdev.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bitratestats.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bpf.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bus_dpaa.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bus_fslmc.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bus_ifpga.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bus_pci.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bus_vdev.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_bus_vmbus.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_cfgfile.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_cmdline.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_common_cpt.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_common_dpaax.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_common_octeontx.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_common_octeontx2.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_compressdev.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_cryptodev.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_distributor.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_eal.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_eal.so.20.0(DPDK_20.0)(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_efd.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_ethdev.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_ethdev.so.20.0(DPDK_20.0)(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_eventdev.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_fib.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_flow_classify.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_gro.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_gso.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_hash.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_ip_frag.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_ipsec.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_jobstats.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_kvargs.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_latencystats.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_lpm.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mbuf.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mbuf.so.20.0(DPDK_20.0)(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_member.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool.so.20.0(DPDK_20.0)(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool_bucket.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool_dpaa.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool_dpaa2.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool_octeontx.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool_octeontx2.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool_ring.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_mempool_stack.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_meter.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_meter.so.20.0(DPDK_20.0)(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_meter.so.20.0(EXPERIMENTAL)(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_metrics.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_net.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pci.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pdump.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pipeline.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_af_packet.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_ark.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_atlantic.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_avp.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_axgbe.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_bbdev_fpga_lte_fec.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_bbdev_null.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_bbdev_turbo_sw.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_bnx2x.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_bnxt.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_bond.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_caam_jr.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_crypto_scheduler.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_cxgbe.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_dpaa.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_dpaa2.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_dpaa2_event.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_dpaa2_sec.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_dpaa_event.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_dpaa_sec.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_dsw_event.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_e1000.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_ena.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_enetc.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_enic.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_failsafe.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_fm10k.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_hinic.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_hns3.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_i40e.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_iavf.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_ice.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_ifc.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_ixgbe.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_lio.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_memif.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_mlx5.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_netvsc.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_nfp.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_nitrox.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_null.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_null_crypto.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_octeontx.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_octeontx2.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_octeontx2_crypto.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_octeontx2_event.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_octeontx_crypto.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_octeontx_ssovf.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_octeontx_zip.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_opdl_event.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_pcap.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_qat.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_qede.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_ring.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_sfc_efx.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_skeleton_event.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_softnic.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_sw_event.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_tap.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_thunderx_nicvf.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_vdev_netvsc.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_vhost.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_virtio.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_virtio_crypto.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_pmd_vmxnet3_uio.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_port.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rawdev.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rawdev_dpaa2_cmdif.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rawdev_dpaa2_qdma.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rawdev_ioat.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rawdev_ntb.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rawdev_octeontx2_dma.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rawdev_skeleton.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rcu.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_reorder.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_rib.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_ring.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_sched.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_security.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_stack.so.0.200()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_table.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_timer.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_vhost.so.20.0()(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
  - nothing provides librte_vhost.so.20.0(DPDK_20.0)(64bit) needed by openvswitch-2.14.0-2.fc33.x86_64
error: with stdout output: : error running rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-296672374/srv/repo:4a5dccf92728fd13c944805aea5e3206d9292b401b075824a76713d9aa749d52 --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4 --custom-origin-description Managed by machine-config-operator: 0 metadata, 0 content objects imported; 0 bytes content written
Checking out tree 4a5dccf...done
Enabled rpm-md repositories: fedora-cisco-openh264 updates-archive
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-08-25T19:10:34Z
rpm-md repo 'updates-archive' (cached); generated: 2021-01-25T03:18:19Z
Importing rpm-md...done
Resolving dependencies...done
: exit status 1
````

Any suggestions?

**Comment by vrutkovs** [comment]
>as already found out master worker rendered config was messed up in the script

Fixed

> The scripts are not fully working for us, the offending command NODE=$(oc get node -l node-role.kubernetes.io/worker= -o=jsonpath='{.items[*].metadata.name}') is not returning a single result

Oh, hmm, updated to use `hostname -f` instead

> and ran into the following error:

Check if `rpm-ostree cleanup -m` cleans up metadata and `pivot` proceeds?
Probably my bash-foo is too weak, maybe we should be using `sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora.repo && sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-updates.repo` instead?

**Comment by holgerstolzenberg** [comment]
The command `rpm-ostree cleanup -m` succeeds, still we have no luck. What we have tried now is:

```bash
rpm-ostree cleanup -m

sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora.repo
sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-updates.repo
sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-updates-archive.repo
sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-cisco-openh264.repo

/run/bin/machine-config-daemon pivot "quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c"
sed -i 's;enabled=0;enabled=1;g' /etc/yum.repos.d/fedora{,-updates}.repo
```

giving the following error:

```
[root@okd-pg-w-03 core]# rpm-ostree cleanup -m
[root@okd-pg-w-03 core]#
[root@okd-pg-w-03 core]# sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora.repo
[root@okd-pg-w-03 core]# sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-updates.repo
[root@okd-pg-w-03 core]# sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-updates-archive.repo
[root@okd-pg-w-03 core]# sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-cisco-openh264.repo
[root@okd-pg-w-03 core]#
[root@okd-pg-w-03 core]# /run/bin/machine-config-daemon pivot "quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c"
I0125 09:13:29.520866    7856 run.go:18] Running: nice -- ionice -c 3 oc image extract --path /:/run/mco-machine-os-content/os-content-629531133 --registry-config /var/lib/kubelet/config.json quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
I0125 09:13:49.599318    7856 rpm-ostree.go:261] Running captured: rpm-ostree status --json
I0125 09:13:49.642793    7856 rpm-ostree.go:179] Previous pivot: quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
I0125 09:13:51.572609    7856 rpm-ostree.go:216] No com.coreos.ostree-commit label found in metadata! Inspecting...
I0125 09:13:51.572639    7856 rpm-ostree.go:261] Running captured: ostree refs --repo /run/mco-machine-os-content/os-content-629531133/srv/repo
I0125 09:13:51.609109    7856 rpm-ostree.go:224] Using ref fedora/x86_64/coreos/next-devel
I0125 09:13:51.609163    7856 rpm-ostree.go:261] Running captured: ostree rev-parse --repo /run/mco-machine-os-content/os-content-629531133/srv/repo fedora/x86_64/coreos/next-devel
I0125 09:13:51.633534    7856 rpm-ostree.go:243] Executing rebase from repo path /run/mco-machine-os-content/os-content-629531133/srv/repo with customImageURL pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c and checksum 14eea5296ffb7a28aff80a70c03434e8034422b0d11b47475b29530b93ab4682
I0125 09:13:51.633569    7856 rpm-ostree.go:261] Running captured: rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-629531133/srv/repo:14eea5296ffb7a28aff80a70c03434e8034422b0d11b47475b29530b93ab4682 --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c --custom-origin-description Managed by machine-config-operator
error: No enabled repositories
error: with stdout output: : error running rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-629531133/srv/repo:14eea5296ffb7a28aff80a70c03434e8034422b0d11b47475b29530b93ab4682 --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c --custom-origin-description Managed by machine-config-operator: 0 metadata, 0 content objects imported; 0 bytes content written
Checking out tree 14eea52...done
: exit status 1
[root@okd-pg-w-03 core]# sed -i 's;enabled=0;enabled=1;g' /etc/yum.repos.d/fedora{,-updates}.repo
```

We are not quite sure if we are using the correct pivot point `"quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c"`

**Comment by holgerstolzenberg** [comment]
In my opinion the most easy way would be to somehow force reinstall `open-vm-tools` so that it can be cleanly removed by the update.

**Comment by vrutkovs** [comment]
`2fe2f` is from previous stable:
```
$ oc adm release info --image-for=machine-os-content quay.io/openshift/okd:4.6.0-0.okd-2021-01-17-185703                                                                     
quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
```
The latest has `64f1..`:
```
$ oc adm release info --image-for=machine-os-content quay.io/openshift/okd:4.6.0-0.okd-2021-01-23-132511                             
quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4
```

>In my opinion the most easy way would be to somehow force reinstall open-vm-tools so that it can be cleanly removed by the update.

#471 is about rpm-ostree unable to install the RPM when the binaries from this RPM are already written to disk (we have to do that so that bootstrap node could have open-vm-tools too).

**Comment by holgerstolzenberg** [comment]
We are confused now. We are on the way from `4.6.0-0.okd-2021-01-17-185703` to `latest (4.6.0-0.okd-2021-01-23-132511)`. Its still not working, no matter what pivot we use, the error is always that there are now repos enabled.

```
rpm-ostree cleanup -m

sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora.repo
sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-updates.repo
sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-updates-archive.repo
sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-cisco-openh264.repo

/run/bin/machine-config-daemon pivot "quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4"
sed -i 's;enabled=0;enabled=1;g' /etc/yum.repos.d/fedora{,-updates}.repo
```

**Comment by RyuunoAelia** [comment]
I personnally did not touch the repositories at all and only used the pivot command and some forcing on the MCO part.

With a lot of patience and manual modifications of the Node objets in the API I managed to make MCO accept the new state.

Some bullet points:
* ssh to the machine and switch to root
* use the `machine-config-daemon pivot` command to manually apply the new update
* reboot the host
* during the reboot process force the MCO state of the machine with `oc edit node` and forcing the current state == desired state (the final state) clean up any error message and set step as "Done"
* wait for the machine to reboot and update the MCO state in the Node if it is in degraded try to fix it. Worst case edit the `/etc/machine-config-daemon/currentconfig` file on the host to reflect the state you actually want

**Comment by vrutkovs** [comment]
>sed -i 's;enabled=1;enabled=0;g' /etc/yum.repos.d/fedora-updates.repo

This disables the repo. I think I typo'd in my comment, it should be `sed -i 's;enabled=0;enabled=1;g' /etc/yum.repos.d/fedora-updates.repo`

**Comment by holgerstolzenberg** [comment]
So that means we should activate the fedora-updates repo?

**Comment by vrutkovs** [comment]
temporarily - yes. machine-os-content already has all necessary dependencies, however its pretty tricky to mount it, so for this one time users should enable fedora/fedora-updates to make rpm-ostree happy.

Note, that repos need to be disabled after the node is fixed - it might backfire on cluster upgrades.

**Comment by holgerstolzenberg** [comment]
Thanks for your help. Could you please provide a clean matrix which repos should be enabled/disabled before/after the pivot call. Something like:

```
BEFORE
fedora ?enabled?
fedora-updates ?enabled?
[*] 

AFTER
fedora ?enabled?
fedora-updates ?disabled?
[*] 
```

**Comment by vrutkovs** [comment]
For pivot you need `fedora` and `fedora-updates`. After pivot its best to probably disable those, unless you're planning to install more RPMs on the host

**Comment by holgerstolzenberg** [comment]
After two days we finally managed to get the update done. The essential point was to overcome the MCO trying to provision a specific pivot point. The procedure itself is very annoying, don't know how this should be done for a large cluster. In the end the last comment from @RyuunoAelia helped us.

So here is our procedure (for each node):

* Set `machineconfiguration.openshift.io/desiredConfig` annotation for the given node to a configuration that does not exist. This will cause MCO to put the node into `degraded` state doing nothing as it can't reliably determine what should be done
* Watch the logs of the corresponding `machine-config-daemon-XXX` pod until you see the degraded state is recognised
* No enter the node via SSH and apply the pivot change suggested by @vrutkovs

```bash
rpm-ostree cleanup -m
sed -i 's;enabled=0;enabled=1;g' /etc/yum.repos.d/fedora.repo
sed -i 's;enabled=0;enabled=1;g' /etc/yum.repos.d/fedora-updates.repo
/run/bin/machine-config-daemon pivot "quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4"
```

* This will create a new pivot point on the machine into which you will have to reboot into
* Before doing the reboot edit the nodes `machineconfiguration.openshift.io/currentConfig` annotation and already point it to the configuration you want to switch to
* Then we had to overwrite the `/etc/machine-config-daemon/currentconfig` file (contents where taken from the target machine config) !! Watch out: there different target configs for master and worker nodes
* Reboot the node
* When its up, fix `machineconfiguration.openshift.io/desiredConfig` to the valid target config, it should now match with the `machineconfiguration.openshift.io/currentConfig` value

The `machine-config-daemon` pod will now pick up the changes. In our case, doing this on the first node, it complained about file content mismatches for some file. We patched them manually to the desired content. 

Here is a list of files we had to patch:

```
/etc/crio/crio.conf.d/00-default
/etc/systemd/system/kubelet.service
/etc/systemd/system/machine-config-daemon-pull.service
/etc/systemd/system/nodeip-configuration.service
/etc/systemd/system/ovs-vswitchd.service.d/10-ovs-vswitchd-restart.conf
```

Then the node got recognised as fully done. We rebooted once again to make sure changes persist - and so they did. We saved the patched files to our bastion and re-used for patching up the other nodes during the procedure what saved a lot of time.

**Comment by holgerstolzenberg** [comment]
In the end I have to admit hat this was quite a tough one, especially if you consider that all we would have needed was an `rpm-ostree install open-vm-tools **--force**`.

Maybe it is also a good idea to make the cluster update a bit more resilient to failures, where it fails uninstalling packages that are already no more present.

**Comment by holgerstolzenberg** [comment]
@vrutkovs & @RyuunoAelia still thanks for your help.

**Comment by vrutkovs** [comment]
>Maybe it is also a good idea to make the cluster update a bit more resilient to failures, when it fails uninstalling packages that are already no more present.

Yeah, sorry about that, I'm surprised we didn't this on our CI - we'll work on improving that.
