### ISSUE TITLE
Update 4.7.0-0.okd-2021-06-04-191031 is stuck not updating node OS - "nothing provides pciutils"

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#668]
Update 4.7.0-0.okd-2021-06-04-191031 is stuck not updating node OS's, what can I do to start the OS upgrades?

Jun 7, 2021, 3:06 PM
The pod disruption budget is preventing further disruption to pods because it is at the minimum allowed level.
View details

Jun 7, 2021, 3:06 PM
The pod disruption budget is preventing further disruption to pods because it is at the minimum allowed level.
View details

Jun 7, 2021, 3:05 PM
The pod disruption budget is preventing further disruption to pods because it is at the minimum allowed level.
View details

Jun 7, 2021, 1:52 PM
Cluster operator machine-config has been degraded for 10 minutes. Operator is degraded because RequiredPoolsFailed and cluster upgrades will be unstable.
View details

Jun 7, 2021, 1:52 PM
Cluster operator machine-config has not been available for 10 minutes. Operator may be down or disabled, cluster will not be kept up to date and upgrades will not be possible.
View details

Jun 7, 2021, 1:43 PM
One or more cluster operators have been blocking minor version cluster upgrades for at least an hour for reason DegradedPool. For more information refer to 

![image](https://user-images.githubusercontent.com/23619505/121081606-eda03780-c7aa-11eb-8f02-6b66a9ab068c.png)

![image](https://user-images.githubusercontent.com/23619505/121081921-58517300-c7ab-11eb-8eb6-adc72e3ff2d2.png)

![image](https://user-images.githubusercontent.com/23619505/121082183-ba11dd00-c7ab-11eb-885f-853146ebda11.png)

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by Bengrunt** [comment]
Hello, I've hit a similar issue (if not the same) on our baremetal preproduction cluster.

All went well during the ClusterOperator upgrades, however nodes didn't recover from their reboot.  
I've got my first master and my first worker nodes stuck in this degraded state.:

```
ClusterVersion: Updating to "4.7.0-0.okd-2021-06-04-191031" from "4.7.0-0.okd-2021-05-22-050008" for 12 hours: Working towards 4.7.0-0.okd-2021-06-04-191031: 70 of 670 done (10% complete)
ClusterOperators:
        clusteroperator/authentication is not available (WellKnownAvailable: The well-known endpoint is not yet available: need at least 3 kube-apiservers, got 2) because APIServerDeploymentDegraded: 1 of 3 requested instances are unavailable for apiserver.openshift-oauth-apiserver ()
WellKnownReadyControllerDegraded: need at least 3 kube-apiservers, got 2
        clusteroperator/dns is degraded because DNS default is degraded
        clusteroperator/etcd is degraded because NodeControllerDegraded: The master nodes not ready: node "kum101.domain.tld" not ready since 2021-06-07 20:58:46 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
EtcdMembersDegraded: 2 of 3 members are available, kum101.domain.tld is unhealthy
        clusteroperator/kube-apiserver is degraded because NodeControllerDegraded: The master nodes not ready: node "kum101.domain.tld" not ready since 2021-06-07 20:58:46 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
        clusteroperator/kube-controller-manager is degraded because NodeControllerDegraded: The master nodes not ready: node "kum101.domain.tld" not ready since 2021-06-07 20:58:46 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
        clusteroperator/kube-scheduler is degraded because NodeControllerDegraded: The master nodes not ready: node "kum101.domain.tld" not ready since 2021-06-07 20:58:46 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
        clusteroperator/machine-config is not available (Cluster not available for 4.7.0-0.okd-2021-06-04-191031) because Failed to resync 4.7.0-0.okd-2021-06-04-191031 because: timed out waiting for the condition during waitForDaemonsetRollout: Daemonset machine-config-daemon is not ready. status: (desired: 6, updated: 6, ready: 4, unavailable: 2)
        clusteroperator/monitoring is not available () because Failed to rollout the stack. Error: running task Updating node-exporter failed: reconciling node-exporter DaemonSet failed: updating DaemonSet object failed: waiting for DaemonSetRollout of openshift-monitoring/node-exporter: got 2 unavailable nodes
        clusteroperator/network is degraded because DaemonSet "openshift-multus/multus" rollout is not making progress - last change 2021-06-07T20:58:47Z
DaemonSet "openshift-ovn-kubernetes/ovnkube-master" rollout is not making progress - last change 2021-06-07T20:58:47Z
DaemonSet "openshift-ovn-kubernetes/ovnkube-node" rollout is not making progress - last change 2021-06-07T20:58:47Z
DaemonSet "openshift-network-diagnostics/network-check-target" rollout is not making progress - last change 2021-06-07T20:58:47Z
        clusteroperator/openshift-apiserver is degraded because APIServerDeploymentDegraded: 1 of 3 requested instances are unavailable for apiserver.openshift-apiserver ()
```

I can't ssh to the degraded master node, even though it booted. I can access the server console via ipmi but I don't know the `root` ou `core` user passwords. Usually I can ssh to them... So I'd like to troubleshoot further but I can't access the nodes. :/ Anyone knows if I can get those passwords? The `oc debug node` command does not work either.

**Comment by Bengrunt** [comment]
> 
> 
> Password authentication is disable on Fedora CoreOS.
> 
> Did those node boot properly? Did they get valid IPs/hostnames?

All I can tell is that it's not answering to pings at the usual IP/hostname. What would be the usual debug course in the kind of situation ? I already did a simple host reboot but to no avail.

**Comment by Bengrunt** [comment]
Oh and the must-gather process fails because when it tries to connect to the affected hosts it gets `no route to host` kind of issues. So yeah that probably means that something went wrong with the OS upgrade with regards to network connectivity. FYI those nodes worked well and underwent several cluster upgrades in the last two months. No config change in our infra iether. :/

I've no idea where to look next :/

**Comment by johnlongo** [comment]
Here is the file

**Comment by johnlongo** [comment]
Looks like the site isn't allowing me to upload the file, it's almost 6 meg, is there another way I can get it to you guy's?

**Comment by johnlongo** [comment]
I broke up the tar into smaller chunks, still need to brake up one more, but wanted to attach what I have so far
[must-gather-1.tar.gz](https://github.com/openshift/okd/files/6618069/must-gather-1.tar.gz)
[must-gather-2.tar.gz](https://github.com/openshift/okd/files/6618070/must-gather-2.tar.gz)
[must-gather-3.tar.gz](https://github.com/openshift/okd/files/6618072/must-gather-3.tar.gz)
[must-gather-4.tar.gz](https://github.com/openshift/okd/files/6618074/must-gather-4.tar.gz)
[must-gather-6.tar.gz](https://github.com/openshift/okd/files/6618075/must-gather-6.tar.gz)

**Comment by vrutkovs** [comment]
>Node master1.ocp4-1.apptecinc.com is reporting: "failed to update OS to quay.io/openshift/okd-content@sha256:c874131a66de67bdaa9764d53b6387a97902626d7fd344f2657b03cd2cd55dd4 ... error: Could not depsolve transaction; 1 problem detected:\n Problem: conflicting requests\n  - nothing provides pciutils needed by open-vm-tools-11.2.5-6.fc34.x86_64\n: exit status 1

**Comment by johnlongo** [comment]
What can I do to fix this?
Can I restart the update in the pod? If so how?

**Comment by johnlongo** [comment]
More files
[must-gather-5-1.tar.gz](https://github.com/openshift/okd/files/6618214/must-gather-5-1.tar.gz)
[must-gather-5-2.tar.gz](https://github.com/openshift/okd/files/6618216/must-gather-5-2.tar.gz)
[must-gather-5-4.tar.gz](https://github.com/openshift/okd/files/6618217/must-gather-5-4.tar.gz)

**Comment by johnlongo** [comment]
Last set of files
[must-gather-5-3-1.tar.gz](https://github.com/openshift/okd/files/6618268/must-gather-5-3-1.tar.gz)
[must-gather-5-3-2.tar.gz](https://github.com/openshift/okd/files/6618270/must-gather-5-3-2.tar.gz)
[must-gather-5-3-3.tar.gz](https://github.com/openshift/okd/files/6618271/must-gather-5-3-3.tar.gz)

**Comment by vrutkovs** [comment]
>What can I do to fix this?
>Can I restart the update in the pod? If so how?

I don't know why this happened in the first place, I haven't seen this issue in CI.

Try this for a workaround. ssh to affected node, run:
* `rpm-ostree uninstall open-vm-tools`
* `sed -i -e 's,enabled=[01],enabled=1,' /etc/yum.repos.d/fedora.repo`
* `rpm-ostree install open-vm-tools` (this should bring in all dependencies)
* restart `machine-config-daemon` pod on this node

Repeat for all masters / workers

**Comment by johnlongo** [comment]
Unistalled open-vm-tools , then tried to install open-vm-tools and got the following error.

[core@master1 ~]$ sudo rpm-ostree install open-vm-tools
Checking out tree 582ab87... done
Enabled rpm-md repositories: fedora fedora-debuginfo fedora-source
rpm-md repo 'fedora' (cached); generated: 2020-10-19T23:27:19Z
rpm-md repo 'fedora-debuginfo' (cached); generated: 2020-10-19T23:24:46Z
rpm-md repo 'fedora-source' (cached); generated: 2020-10-19T23:27:54Z
Importing rpm-md... done
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: cannot install both NetworkManager-1:1.26.2-2.fc33.x86_64 and NetworkManager-1:1.26.8-1.fc33.x86_64
  - package NetworkManager-ovs-1:1.26.2-2.fc33.x86_64 requires NetworkManager(x86-64) = 1:1.26.2-2.fc33, but none of the providers can be installed
  - conflicting requests
[core@master1 ~]$

**Comment by vrutkovs** [comment]
Hmm, with repos enabled (step 2), try `rpm-ostree update` as well?

**Comment by johnlongo** [comment]
I got the update to happen by using this seq:

sudo rpm-ostree uninstall open-vm-tools
sudo sed -i -e 's,enabled=[01],enabled=1,' /etc/yum.repos.d/fedora.repo
sudo sed -i -e 's,enabled=[01],enabled=2,' /etc/yum.repos.d/fedora-updates.repo
sudo rpm-ostree install open-vm-tools 
sudo sed -i -e 's,enabled=[01],enabled=0,' /etc/yum.repos.d/fedora.repo
sudo sed -i -e 's,enabled=[01],enabled=0,' /etc/yum.repos.d/fedora-updates.repo
sudo systemctl reboot

But the os is not getting upgraded 

![image](https://user-images.githubusercontent.com/23619505/121240808-c019c380-c868-11eb-987f-258e8a85e1f3.png)

**Comment by Wolskie** [comment]
Seeing the same issue as @johnlongo on my baremetal deployment.

```
Jun 09 00:38:23 worker-0.ocp.hahl.id.au rpm-ostree[54949]: Txn UpdateDeployment on /org/projectatomic/rpmostree1/fedora_coreos failed: Could not depsolve transaction; 1 problem detected:
                                                            Problem: conflicting requests
                                                             - nothing provides pciutils needed by open-vm-tools-11.2.5-6.fc34.x86_64
```

**Comment by johnlongo** [comment]
I punted and restored a backup I had.

**Comment by johnlongo** [comment]
After restoring and trying the update again, looks like to update step zram::generator isn't finding a configuration file (looks like some device config) and exits, it goes into a loop trying to find the file and exits. see attached

![image](https://user-images.githubusercontent.com/23619505/121491749-3cfd8800-c9a4-11eb-88a5-ed724dc38029.png)

**Comment by devzeronull** [comment]
I can confirm this problem, having the same as described from @johnlongo with bare-metal UPI Installation on VMware.

We were doing an incremental upgrade test with an freshly installed ""4.7.0-0.okd-2021-04-24-103438", upgrading it seemlessly to "4.7.0-0.okd-2021-05-22-050008" and stucking in upgrading from there to "4.7.0-0.okd-2021-06-04-191031" when rolling out machine-configs.

The console shows exactly the same as @johnlongo described:
One Master node shows:
![grafik](https://user-images.githubusercontent.com/77630137/121716843-d2059b80-cae0-11eb-8240-cc266700f512.png)
With message:
```
Message:               Node master01.xxx.xxx is reporting: "failed to update OS to quay.io/openshift/okd-content@sha256:c874131a66de67bdaa9764d53b6387a97902626d7fd344f2657b03cd2cd55dd4 : error running ostree refs --repo /run/mco-machine-os-content/os-content-215275653/srv/repo: error: opening repo: opendir(/run/mco-machine-os-content/os-content-215275653/srv/repo): No such file or directory\n: exit status 1"
Reason:                1 nodes are reporting degraded status on sync
```

One Worker Node the same:
![grafik](https://user-images.githubusercontent.com/77630137/121716951-f3668780-cae0-11eb-9862-618708c4ed46.png)
With message:
```
Message:               Node worker01.xxx.xxx is reporting: "failed to update OS to quay.io/openshift/okd-content@sha256:c874131a66de67bdaa9764d53b6387a97902626d7fd344f2657b03cd2cd55dd4 : error running ostree refs --repo /run/mco-machine-os-content/os-content-373308105/srv/repo: error: opening repo: opendir(/run/mco-machine-os-content/os-content-373308105/srv/repo): No such file or directory\n: exit status 1"
Reason:                1 nodes are reporting degraded status on sync
```

All Operators got updated:
![grafik](https://user-images.githubusercontent.com/77630137/121717027-0b3e0b80-cae1-11eb-98fa-d80c02dd6b0b.png)

Failing conditions are:
![grafik](https://user-images.githubusercontent.com/77630137/121717179-30cb1500-cae1-11eb-84ee-d578ebcadcb9.png)

Interestingly 2 worker nodes got already updated:
![grafik](https://user-images.githubusercontent.com/77630137/121718052-23faf100-cae2-11eb-8d6a-21f9884fa5f9.png)

I can SSH into the machines and systemd repeats a sequence and errors, e.g.:
```
Jun 11 16:29:23 master01.xxx.xxx zram_generator::config[196476]: No configuration file found.
Jun 11 16:29:23 master01.xxx.xxx zram_generator::generator[196476]: No devices configured, exiting.
Jun 11 16:29:23 master01.xxx.xxx coreos-boot-mount-generator: using dev-disk-by\x2dlabel-boot for boot mount to /boot
Jun 11 16:29:23 master01.xxx.xxx systemd[1]: /usr/lib/systemd/system/ovs-vswitchd.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvswitch/ovs-vswitchd.pid → /run/openvswitch/ovs-vswitchd.pid; please update the unit file accordingly.
Jun 11 16:29:23 master01.xxx.xxx systemd[1]: /usr/lib/systemd/system/ovsdb-server.service:10: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvswitch/ovsdb-server.pid → /run/openvswitch/ovsdb-server.pid; please update the unit file accordingly.
Jun 11 16:29:23 master01.xxx.xxx systemd[1]: /usr/lib/systemd/system/docker.socket:6: ListenStream= references a path below legacy directory /var/run/, updating /var/run/docker.sock → /run/docker.sock; please update the unit file accordingly.
```

I then drained the two nodes that stucked with the symptoms described before and changed their annotations as long as flushed the journal on the nodes terminal to Reset the MCO degraded status, rebooted them and marked them as schedulable meanwhile.

The MCO processed another two worker nodes successfully (so in total 4 Nodes with new MCs/CoreOS versions are uptodate) and came back to the previouse stucking nodes having the same errors again.

When I then drained and deleted the problematic worker01 node and provisioned it new everything in the end worked flawlessly with it and we got now in total 5 worker nodes (instead 2 when the error started) got upgraded.

So in the end I would guess that there is something going really wrong with the MCO becoming unreliable, I would like to investigate it deeper, do you have any clues?
(Btw. we had exactly the same issue with Release "4.7.0-0.okd-2021-04-11-124433" and thought it was a faulty release as the JUnit tests let us assume)

Best regards

**Comment by vrutkovs** [comment]
Fixed in https://github.com/openshift/okd/releases/tag/4.7.0-0.okd-2021-06-13-090745 - `machine-os-content` has all RPMs installed in ostree config, so issues like missing dependencies are no longer threatening us.

Please check if updating to a new release fixes it (this should work from broken upgrade cluster too)

**Comment by johnlongo** [comment]
cant find the update:

oc patch clusterversion/version --type=merge --patch '{"spec":{"upstream":"https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/graph"}}'

oc adm upgrade --force --to=4.7.0-0.okd-2021-06-13-090745 --allow-upgrade-with-warnings=true --allow-explicit-upgrade=true

error: The update 4.7.0-0.okd-2021-06-13-090745 is not one of the available updates: 4.7.0-0.okd-2021-06-04-191031

**Comment by johnlongo** [comment]
4.7.0-0.okd-2021-06-13-090745 worked.
Thank You
![image](https://user-images.githubusercontent.com/23619505/121833092-919d4d80-cc99-11eb-8bcb-2c094fe00602.png)

**Comment by devzeronull** [comment]
Thanks for the new release, but this didn't fix it for now...

At least after starting upgrade to "4.7.0-0.okd-2021-06-13-090745" a master which could not be upgraded before was upgraded, but CoreOS seems to get a nightly build "Fedora CoreOS 34 47.34.202106101121-0" - is this intended?

**Comment by devzeronull** [comment]
@johnlongo which CoreOS are your Nodes now using after the Upgrade?

**Comment by johnlongo** [comment]
v1.20.0+2817867-1077
![image](https://user-images.githubusercontent.com/23619505/121970114-d41b6480-cd43-11eb-848e-d981a5190732.png)

**Comment by devzeronull** [comment]
Hi, thanks for the information, but this displays the Kubernetes Version, the CoreOS Version could be shown e.g. with argument "-o wide", with "oc describe nodes" or in the yaml output.

So it would be kind if you could take a look with e.g. "oc get nodes -o wide"

Best regards

**Comment by vrutkovs** [comment]
>get a nightly build "Fedora CoreOS 34 47.34.202106101121-0" - is this intended?

Yes. the nodes would simply report as "Fedora CoreOS" in `/etc/os-release. This is due to a new way of building os-contents, where we use Fedora configuration and mix in additional RPMs. As a result version string is mutated. This is not a nightly build (as in "untested")
